### ISSUE TITLE
QCA7000 Flashing Tools not working

### ISSUE THREAD

**Issue by isaaceichelberger** [devolo/dlan-greenphy-sdk#17]
When attempting to use ./qca7000-update.sh, I am only being prompted to the usage script. It seems that the avreadpib script that the update script calls cannot read the MAC address of my dLAN board. Even when I supply the MAC address, it still gives me the usage response. What step am I missing here?

I've tried this on two windows machines as well as a raspberry pi running raspbian.

**Comment by Molkenbur** [comment]
I will check this week.

**Comment by Molkenbur** [comment]
Hi isaaceichelberger, 

for Windows there is another archive to be used: https://github.com/devolo/dlan-greenphy-sdk/blob/master/QCA7000_GreenPHY_Firmware/qca7000_1-2-4-00-1_kit_2018-05-08_windows.zip
I assume, you used this for Windows. 
Have you provided the profile you want to configure? Default is iot-conform. 
If this is not the problem, then it might help, if you share the call and the output of the command within this case.

Regards
Thomas

**Comment by isaaceichelberger** [comment]
Hey, thanks for your reply.

That's what I've been trying, it seems to not recognize the board, whether or not I supply to the MAC address. 

```
C:\Users\isaac\Downloads\qca7000_1-2-4-00-1_kit_2018-05-08_windows (1)\qca7000_1-2-4-00-1_kit\windows>qca7000-update.cmd iot-conform
CFG: iot-conform
Usage:
qca7000-update <config-profile> [mac-address]

 config-profile must be one of:

  iot-generic    IoT generic, optimized for performance: 50561 off (SLAC off)
  iot-conform    IoT over mains, optimized for conformity: 50561 on (SLAC off)
  emob-charger   e-mobility use as charging station: SLAC in EVSE mode (50561 off)
  emob-vehicle   e-mobility use as vehicle: SLAC in PEV mode (50561 off)

 mac-address is optional, if omitted, the first
 localy attached adapter will be programmed

C:\Users\isaac\Downloads\qca7000_1-2-4-00-1_kit_2018-05-08_windows (1)\qca7000_1-2-4-00-1_kit\windows>qca7000-update.cmd iot-conform BCF2AFF1E6FE
CFG: iot-conform
Usage:
qca7000-update <config-profile> [mac-address]

 config-profile must be one of:

  iot-generic    IoT generic, optimized for performance: 50561 off (SLAC off)
  iot-conform    IoT over mains, optimized for conformity: 50561 on (SLAC off)
  emob-charger   e-mobility use as charging station: SLAC in EVSE mode (50561 off)
  emob-vehicle   e-mobility use as vehicle: SLAC in PEV mode (50561 off)

 mac-address is optional, if omitted, the first
 localy attached adapter will be programmed
```
 

 I've also tried modifying the script, where I hardcoded the MAC address and other information about the board, and this is the output when I use that script:

```
C:\Users\isaac\Downloads\qca7000_1-2-5-00-1_kit_2019-08-22_windows\qca7000_1-2-5-00-1_kit\windows>qca7000-update.cmd iot-conform
CFG: iot-conform
MAC: BCF2AFF1E6FE
DAK: 8046201
MFT: "devolo dLAN Green PHY Module [MT2489]"
dLAN was unexpected at this time.
```

**Comment by koljanowak** [comment]
It seems the script cannot find your board. Yes, it would have been more nice if the script had told you that, instead of showing the command line help again. Going to fix that in the future.

If I'm correct and this is the reason, hardcoding the MAC in the script is not going to help, it will only break the script at a later point because some data read from the board will be missing. 

Can you please call avreadpib.exe (in the same directory) directly? It should either say "Saving as (MAC).pib" or "Device not found", and from your output I assume it will be the latter. 

The script uses the executables in the same directory, like avreadpib.exe, to find and configure the board. Those tools require a packet capture driver to send and receive special layer2 frames. If you have installed devolo Cockpit [1], this driver is already installed. As an alternative, you could also install WinPCAP [2], the driver which is used by Wireshark.

After making sure one of those is installed, you can retry avreadpib.exe and see if it now says "Saving as ...". Then the script should also work.

If avreadpib.exe still says "Device not found", I would assume your board is broken or not correctly attached.

[1] https://www.devolo.de/support/downloads/download/devolo-cockpit
[2] https://www.winpcap.org/install/bin/WinPcap_4_1_3.exe

**Comment by koljanowak** [comment]
I improved the README_windows.txt to mention the packet capture driver, and the update script itself to tell you if the device was not found.

https://github.com/devolo/dlan-greenphy-sdk/blob/master/QCA7000_GreenPHY_Firmware/qca7000_1-2-4-00-1_kit_2022-03-11_windows.zip

**Comment by isaaceichelberger** [comment]
Thank you, the packet capture driver was the missing piece to get the firmware onto the board. 

I'm using this board in conjunction with RISE-V2G to be able to communicate with a charging station or EV. Do you know if I would need to switch the firmware between "emob-charger" and "emob-vehicle" when I'm emulating the separate parts, or should "iot-conform" be sufficient?

**Comment by Molkenbur** [comment]
I am not experienced with EV charging application, but I assume, that you should configure the GreenPhy Module accordingly.

**Comment by Molkenbur** [comment]
Happy, that you were now are to update and configure the GreenPhy firmware. On our PCs, the capture driver is typically already installed and therefore, we are not facing this issue. Many thanks to Kolja for clarification and improving documentation as well as the update script!
